### ISSUE TITLE
Error on load: Expects different interface version

### ISSUE THREAD

**Issue by mogulbgod** [ThornyFFXI/Sequencer#1]
1.01b when loaded says "Plugin is compiled with a different interface version than expected" and it expects to find 4.15

This is being loaded for the first time with luAshitaCast 2.02 being loaded for the first time on a fresh install.

**Comment by ThornyFFXI** [comment]
Plugins must match the Ashita version they're being loaded on.  If you're on Ashita 4.15, you should use the release labeled Ashita 4.15, which is at time of this issue:

https://github.com/ThornyFFXI/Sequencer/releases/tag/1.01

**Comment by mogulbgod** [comment]
It says "Plugin: 4.16, Expected 4.15" and I'm currently on Ashita v. 4.1.0.2

**Comment by ThornyFFXI** [comment]
Yes, you downloaded the latest, which is for Ashita Interface 4.16  (you can type /aver to see your interface version).  You are on Ashita Interface 4.15, which is outdated.  You will need to download the version for Ashita Interface 4.15, that I have linked above.  This is not a bug, and this type of question belongs on ashita discord not the issue tracker.
